//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoachingPlan.Resource.Messages.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço não encontrado.
        /// </summary>
        public static string AddressNotFound {
            get {
                return ResourceManager.GetString("AddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo corpo da menssagem é necessário.
        /// </summary>
        public static string BodyMessageIsRequired {
            get {
                return ResourceManager.GetString("BodyMessageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo classificação é necessário.
        /// </summary>
        public static string ClassificationIsRequired {
            get {
                return ResourceManager.GetString("ClassificationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coachee não encontrado.
        /// </summary>
        public static string CoacheeNotFound {
            get {
                return ResourceManager.GetString("CoacheeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coach não encontrado.
        /// </summary>
        public static string CoachNotFound {
            get {
                return ResourceManager.GetString("CoachNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo data é necessário.
        /// </summary>
        public static string DataIsRequired {
            get {
                return ResourceManager.GetString("DataIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo data é necessário.
        /// </summary>
        public static string DateIsRequired {
            get {
                return ResourceManager.GetString("DateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo destinatário é necessário.
        /// </summary>
        public static string DestinationIsRequired {
            get {
                return ResourceManager.GetString("DestinationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo fim é necessário.
        /// </summary>
        public static string EndTimeIsRequired {
            get {
                return ResourceManager.GetString("EndTimeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo enunciado é necesário.
        /// </summary>
        public static string EnuciationIsRequired {
            get {
                return ResourceManager.GetString("EnuciationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login falhou.
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo indicador é necessário.
        /// </summary>
        public static string IndicatorIsRequired {
            get {
                return ResourceManager.GetString("IndicatorIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de endereço inválido.
        /// </summary>
        public static string InvalidAddresType {
            get {
                return ResourceManager.GetString("InvalidAddresType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento inválida.
        /// </summary>
        public static string InvalidBirthDate {
            get {
                return ResourceManager.GetString("InvalidBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corpo da mensagem inválido.
        /// </summary>
        public static string InvalidBodyMessage {
            get {
                return ResourceManager.GetString("InvalidBodyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP inválido.
        /// </summary>
        public static string InvalidCEP {
            get {
                return ResourceManager.GetString("InvalidCEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade inválida.
        /// </summary>
        public static string InvalidCity {
            get {
                return ResourceManager.GetString("InvalidCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classe inválide.
        /// </summary>
        public static string InvalidClassStrongPoint {
            get {
                return ResourceManager.GetString("InvalidClassStrongPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ inválido.
        /// </summary>
        public static string InvalidCNPJ {
            get {
                return ResourceManager.GetString("InvalidCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF inválido.
        /// </summary>
        public static string InvalidCPF {
            get {
                return ResourceManager.GetString("InvalidCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados Inválidos.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do DDD deve conter 2 digítos.
        /// </summary>
        public static string InvalidDDD {
            get {
                return ResourceManager.GetString("InvalidDDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriçaõ inválida.
        /// </summary>
        public static string InvalidDescription {
            get {
                return ResourceManager.GetString("InvalidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail inválido.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enunciado inválido.
        /// </summary>
        public static string InvalidEnunciation {
            get {
                return ResourceManager.GetString("InvalidEnunciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gênero inválido.
        /// </summary>
        public static string InvalidGenre {
            get {
                return ResourceManager.GetString("InvalidGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicador inválido.
        /// </summary>
        public static string InvalidIndicator {
            get {
                return ResourceManager.GetString("InvalidIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome inválido.
        /// </summary>
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número inválido.
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do número de telefone deve conter 8 digítos.
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profissão inválida.
        /// </summary>
        public static string InvalidProfession {
            get {
                return ResourceManager.GetString("InvalidProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resposta inválida.
        /// </summary>
        public static string InvalidReply {
            get {
                return ResourceManager.GetString("InvalidReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidade inválida.
        /// </summary>
        public static string InvalidSpecialty {
            get {
                return ResourceManager.GetString("InvalidSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado inválido.
        /// </summary>
        public static string InvalidState {
            get {
                return ResourceManager.GetString("InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status inválido.
        /// </summary>
        public static string InvalidStatus {
            get {
                return ResourceManager.GetString("InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rua inválida.
        /// </summary>
        public static string InvalidStreet {
            get {
                return ResourceManager.GetString("InvalidStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto forte inválido.
        /// </summary>
        public static string InvalidStrongPoint {
            get {
                return ResourceManager.GetString("InvalidStrongPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assunto inválido.
        /// </summary>
        public static string InvalidSubject {
            get {
                return ResourceManager.GetString("InvalidSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema inválido.
        /// </summary>
        public static string InvalidTheme {
            get {
                return ResourceManager.GetString("InvalidTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formação inválida.
        /// </summary>
        public static string InvalidTraining {
            get {
                return ResourceManager.GetString("InvalidTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragilidade inválida.
        /// </summary>
        public static string InvalidWeakness {
            get {
                return ResourceManager.GetString("InvalidWeakness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário bloqueado.
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo modo é necessário.
        /// </summary>
        public static string ModeIsRequired {
            get {
                return ResourceManager.GetString("ModeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nme é necessário.
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nota é necessário.
        /// </summary>
        public static string NoteIsRequired {
            get {
                return ResourceManager.GetString("NoteIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa não encontrada.
        /// </summary>
        public static string PersonNotFound {
            get {
                return ResourceManager.GetString("PersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone não encontrado.
        /// </summary>
        public static string PhoneNotFound {
            get {
                return ResourceManager.GetString("PhoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo preço é necessário.
        /// </summary>
        public static string PriceIsRequired {
            get {
                return ResourceManager.GetString("PriceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo proposta é necessário.
        /// </summary>
        public static string ProposalIsRequired {
            get {
                return ResourceManager.GetString("ProposalIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro falhou.
        /// </summary>
        public static string RegistrationFailure {
            get {
                return ResourceManager.GetString("RegistrationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo resposta é necessário.
        /// </summary>
        public static string ReplyIsRequired {
            get {
                return ResourceManager.GetString("ReplyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificação necessária.
        /// </summary>
        public static string RequiresVerification {
            get {
                return ResourceManager.GetString("RequiresVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo preço da sessão é necessário.
        /// </summary>
        public static string SessionPriceIsRequired {
            get {
                return ResourceManager.GetString("SessionPriceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidade não encontrada.
        /// </summary>
        public static string SpecialtyNotFound {
            get {
                return ResourceManager.GetString("SpecialtyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo  data inicial é necessário.
        /// </summary>
        public static string StartDateIsRequired {
            get {
                return ResourceManager.GetString("StartDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo início é necessário.
        /// </summary>
        public static string StartTimeIsRequired {
            get {
                return ResourceManager.GetString("StartTimeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto Forte não encontrado.
        /// </summary>
        public static string StrongPointNotFound {
            get {
                return ResourceManager.GetString("StrongPointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo assunto é necessário.
        /// </summary>
        public static string SujectIsRequired {
            get {
                return ResourceManager.GetString("SujectIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo prazo é necessário.
        /// </summary>
        public static string TermGoalIsRequired {
            get {
                return ResourceManager.GetString("TermGoalIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formação não encontrada.
        /// </summary>
        public static string TrainingNotFound {
            get {
                return ResourceManager.GetString("TrainingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo tipo é necessário.
        /// </summary>
        public static string TypeIsRequired {
            get {
                return ResourceManager.GetString("TypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo valor é necessário.
        /// </summary>
        public static string ValueIsRequired {
            get {
                return ResourceManager.GetString("ValueIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo data de verificação é necessário.
        /// </summary>
        public static string VerificationDataIsRequired {
            get {
                return ResourceManager.GetString("VerificationDataIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragilidade não encontrada.
        /// </summary>
        public static string WeaknessNotFound {
            get {
                return ResourceManager.GetString("WeaknessNotFound", resourceCulture);
            }
        }
    }
}
