//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoachingPlan.Resource.Messages.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coachee não encontrado.
        /// </summary>
        public static string CoacheeNotFound {
            get {
                return ResourceManager.GetString("CoacheeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coach não encontrado.
        /// </summary>
        public static string CoachNotFound {
            get {
                return ResourceManager.GetString("CoachNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço não encontrado.
        /// </summary>
        public static string EnderecoNotFound {
            get {
                return ResourceManager.GetString("EnderecoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login falhou.
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP inválido.
        /// </summary>
        public static string InvalidCEP {
            get {
                return ResourceManager.GetString("InvalidCEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade inválida.
        /// </summary>
        public static string InvalidCidade {
            get {
                return ResourceManager.GetString("InvalidCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classe inválide.
        /// </summary>
        public static string InvalidClassStrongPoint {
            get {
                return ResourceManager.GetString("InvalidClassStrongPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ inválido.
        /// </summary>
        public static string InvalidCNPJ {
            get {
                return ResourceManager.GetString("InvalidCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF inválido.
        /// </summary>
        public static string InvalidCPF {
            get {
                return ResourceManager.GetString("InvalidCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados Inválidos.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento inválida.
        /// </summary>
        public static string InvalidDataNascimento {
            get {
                return ResourceManager.GetString("InvalidDataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do DDD deve conter 2 digítos.
        /// </summary>
        public static string InvalidDDD {
            get {
                return ResourceManager.GetString("InvalidDDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriçaõ inválida.
        /// </summary>
        public static string InvalidDescricao {
            get {
                return ResourceManager.GetString("InvalidDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail inválido.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado inválido.
        /// </summary>
        public static string InvalidEstado {
            get {
                return ResourceManager.GetString("InvalidEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gênero inválido.
        /// </summary>
        public static string InvalidGenero {
            get {
                return ResourceManager.GetString("InvalidGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome inválido.
        /// </summary>
        public static string InvalidNome {
            get {
                return ResourceManager.GetString("InvalidNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número inválido.
        /// </summary>
        public static string InvalidNumero {
            get {
                return ResourceManager.GetString("InvalidNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profissão inválida.
        /// </summary>
        public static string InvalidProfession {
            get {
                return ResourceManager.GetString("InvalidProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rua inválida.
        /// </summary>
        public static string InvalidRua {
            get {
                return ResourceManager.GetString("InvalidRua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidade inválida.
        /// </summary>
        public static string InvalidSpecialty {
            get {
                return ResourceManager.GetString("InvalidSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status inválido.
        /// </summary>
        public static string InvalidStatus {
            get {
                return ResourceManager.GetString("InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto forte inválido.
        /// </summary>
        public static string InvalidStrongPoint {
            get {
                return ResourceManager.GetString("InvalidStrongPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do número de telefone deve conter 8 digítos.
        /// </summary>
        public static string InvalidTelefone {
            get {
                return ResourceManager.GetString("InvalidTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de endereço inválido.
        /// </summary>
        public static string InvalidTipoEndereco {
            get {
                return ResourceManager.GetString("InvalidTipoEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formação inválida.
        /// </summary>
        public static string InvalidTraining {
            get {
                return ResourceManager.GetString("InvalidTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragilidade inválida.
        /// </summary>
        public static string InvalidWeakness {
            get {
                return ResourceManager.GetString("InvalidWeakness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário bloqueado.
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa não encontrada.
        /// </summary>
        public static string PersonNotFound {
            get {
                return ResourceManager.GetString("PersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificação necessária.
        /// </summary>
        public static string RequiresVerification {
            get {
                return ResourceManager.GetString("RequiresVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidade não encontrada.
        /// </summary>
        public static string SpecialtyNotFound {
            get {
                return ResourceManager.GetString("SpecialtyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto Forte não encontrado.
        /// </summary>
        public static string StrongPointNotFound {
            get {
                return ResourceManager.GetString("StrongPointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone não encontrado.
        /// </summary>
        public static string TelefoneNotFound {
            get {
                return ResourceManager.GetString("TelefoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formação não encontrada.
        /// </summary>
        public static string TrainingNotFound {
            get {
                return ResourceManager.GetString("TrainingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragilidade não encontrada.
        /// </summary>
        public static string WeaknessNotFound {
            get {
                return ResourceManager.GetString("WeaknessNotFound", resourceCulture);
            }
        }
    }
}
