//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class a10_orcamento_tb
    {
        public int ID_PROPOSTA { get; set; }
        public int ID_PROCESSO { get; set; }
        public string PROPOSTA { get; set; }
        public float PRECO_PROPOSTA { get; set; }
        public System.DateTime DATA_PROPOSTA { get; set; }
        public float PRECO_SESSAO { get; set; }
    
        public virtual a9_processo_coaching_tb a9_processo_coaching_tb { get; set; }
    }
}
