//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class a11_sessao_tb
    {
        public a11_sessao_tb()
        {
            this.a12_tarefa_tb = new HashSet<a12_tarefa_tb>();
            this.a17_avaliacao_tb = new HashSet<a17_avaliacao_tb>();
        }
    
        public int ID_SESSAO { get; set; }
        public int ID_PROCESSO { get; set; }
        public string ID_USUARIO { get; set; }
        public string TEMA_SESSAO { get; set; }
        public System.DateTime DATA_SESSAO { get; set; }
        public System.TimeSpan INICIO_SESSAO { get; set; }
        public Nullable<System.TimeSpan> FIM_SESSAO { get; set; }
        public string CLASSIFICACAO_SESSAO { get; set; }
        public string OBSERVACAO_SESSAO { get; set; }
    
        public virtual a4_usuario_tb a4_usuario_tb { get; set; }
        public virtual ICollection<a12_tarefa_tb> a12_tarefa_tb { get; set; }
        public virtual ICollection<a17_avaliacao_tb> a17_avaliacao_tb { get; set; }
        public virtual a9_processo_coaching_tb a9_processo_coaching_tb { get; set; }
    }
}
