//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class a12_tarefa_tb
    {
        public int ID_TAREFA { get; set; }
        public int ID_SESSAO { get; set; }
        public int ID_META { get; set; }
        public System.DateTime DATA_INICIO { get; set; }
        public System.DateTime DATA_REALIZACAO { get; set; }
        public System.DateTime DATA_VERIFICACAO { get; set; }
        public string DESCRICAO_TAREFA { get; set; }
    
        public virtual a11_sessao_tb a11_sessao_tb { get; set; }
        public virtual a16_meta_tb a16_meta_tb { get; set; }
    }
}
