//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class a13_plano_acao_tb
    {
        public a13_plano_acao_tb()
        {
            this.a15_objetivo_tb = new HashSet<a15_objetivo_tb>();
        }
    
        public int ID_PLANO_ACAO { get; set; }
        public int ID_PROCESSO { get; set; }
        public string DESCRICAO_PLANO_ACAO { get; set; }
    
        public virtual ICollection<a15_objetivo_tb> a15_objetivo_tb { get; set; }
        public virtual a9_processo_coaching_tb a9_processo_coaching_tb { get; set; }
    }
}
