//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class a15_objetivo_tb
    {
        public a15_objetivo_tb()
        {
            this.a16_meta_tb = new HashSet<a16_meta_tb>();
        }
    
        public int ID_OBJETIVO { get; set; }
        public string DESCRICAO_OBJETIVO { get; set; }
        public int ID_PLANO_ACAO { get; set; }
    
        public virtual a13_plano_acao_tb a13_plano_acao_tb { get; set; }
        public virtual ICollection<a16_meta_tb> a16_meta_tb { get; set; }
    }
}
