//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class a17_avaliacao_tb
    {
        public int ID_AVALIACAO { get; set; }
        public int ID_SESSAO { get; set; }
        public string ID_USUARIO { get; set; }
        public float NOTA_AVALIACAO { get; set; }
        public string OBSERVACAO_AVALIACAO { get; set; }
    
        public virtual a11_sessao_tb a11_sessao_tb { get; set; }
        public virtual a4_usuario_tb a4_usuario_tb { get; set; }
    }
}
