//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class a18_servico_tb
    {
        public a18_servico_tb()
        {
            this.a9_processo_coaching_tb = new HashSet<a9_processo_coaching_tb>();
        }
    
        public int ID_SERVICO { get; set; }
        public string NOME_SERVICO { get; set; }
        public float PRECO_SERVICO { get; set; }
        public string DESC_SERVICO { get; set; }
    
        public virtual ICollection<a9_processo_coaching_tb> a9_processo_coaching_tb { get; set; }
    }
}
