//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class a1_pessoa_tb
    {
        public a1_pessoa_tb()
        {
            this.a2_telefone_tb = new HashSet<a2_telefone_tb>();
            this.a3_endereco_tb = new HashSet<a3_endereco_tb>();
            this.a4_usuario_tb = new HashSet<a4_usuario_tb>();
        }
    
        public int ID_PESSOA { get; set; }
        public string NOME_PESSOA { get; set; }
        public string CPF_PESSOA { get; set; }
        public System.DateTime DATA_NASC_PESSOA { get; set; }
        public string GENERO_PESSOA { get; set; }
        public bool ATIVO_PESSOA { get; set; }
        public string FOTO_PESSOA { get; set; }
    
        public virtual ICollection<a2_telefone_tb> a2_telefone_tb { get; set; }
        public virtual ICollection<a3_endereco_tb> a3_endereco_tb { get; set; }
        public virtual ICollection<a4_usuario_tb> a4_usuario_tb { get; set; }
    }
}
