//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class a20_questao_tb
    {
        public a20_questao_tb()
        {
            this.a21_resposta_tb = new HashSet<a21_resposta_tb>();
        }
    
        public int ID_QUESTAO { get; set; }
        public int ID_FERRAMENTA { get; set; }
        public string TIPO_RESPOSTA { get; set; }
        public string TIPO_QUESTAO { get; set; }
        public string FASE_QUESTAO { get; set; }
        public Nullable<int> PASSO_QUESTAO { get; set; }
        public string ENUNCIADO_QUESTAO { get; set; }
        public string INSTRUNCAO_QUESTAO { get; set; }
    
        public virtual a19_ferramenta_tb a19_ferramenta_tb { get; set; }
        public virtual ICollection<a21_resposta_tb> a21_resposta_tb { get; set; }
    }
}
