//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class a2_telefone_tb
    {
        public int ID_TELEFONE { get; set; }
        public int ID_PESSOA { get; set; }
        public string DDD_TELEFONE { get; set; }
        public string TELEFONE { get; set; }
        public string DESCRICAO_TELEFONE { get; set; }
    
        public virtual a1_pessoa_tb a1_pessoa_tb { get; set; }
    }
}
