//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class a3_endereco_tb
    {
        public int ID_ENDERECO { get; set; }
        public int ID_PESSOA { get; set; }
        public string CEP_ENDERECO { get; set; }
        public string ESTADO_ENDERECO { get; set; }
        public string CIDADE_ENDERECO { get; set; }
        public string RUA_ENDERECO { get; set; }
        public int NUMERO_ENDERECO { get; set; }
    
        public virtual a1_pessoa_tb a1_pessoa_tb { get; set; }
    }
}
