//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class a4_usuario_tb
    {
        public a4_usuario_tb()
        {
            this.a11_sessao_tb = new HashSet<a11_sessao_tb>();
            this.a17_avaliacao_tb = new HashSet<a17_avaliacao_tb>();
            this.a22_mensagem_tb = new HashSet<a22_mensagem_tb>();
            this.a6_coachee_tb = new HashSet<a6_coachee_tb>();
            this.a5_coach_tb = new HashSet<a5_coach_tb>();
            this.t2_claims_tb = new HashSet<t2_claims_tb>();
            this.t1_logins_tb = new HashSet<t1_logins_tb>();
            this.t4_usuario_papel_tb = new HashSet<t4_usuario_papel_tb>();
        }
    
        public string ID_USUARIO { get; set; }
        public int ID_PESSOA { get; set; }
        public string EMAIL { get; set; }
        public bool EMAILCONFIRMADO { get; set; }
        public string PASSWORDHASH { get; set; }
        public string SECURITYSTAMP { get; set; }
        public string NUMEROTELEFONE { get; set; }
        public bool NUMEROTELEFONECONFIRMADO { get; set; }
        public bool TWOFACTORENABLE { get; set; }
        public Nullable<System.DateTime> LOCKOUTENDDATEUTC { get; set; }
        public bool LOCKOUTENABLE { get; set; }
        public int ACESSFAILEDCOUNT { get; set; }
        public string USERNAME { get; set; }
        public string DISCRIMINATOR { get; set; }
    
        public virtual a1_pessoa_tb a1_pessoa_tb { get; set; }
        public virtual ICollection<a11_sessao_tb> a11_sessao_tb { get; set; }
        public virtual ICollection<a17_avaliacao_tb> a17_avaliacao_tb { get; set; }
        public virtual ICollection<a22_mensagem_tb> a22_mensagem_tb { get; set; }
        public virtual ICollection<a6_coachee_tb> a6_coachee_tb { get; set; }
        public virtual ICollection<a5_coach_tb> a5_coach_tb { get; set; }
        public virtual ICollection<t2_claims_tb> t2_claims_tb { get; set; }
        public virtual ICollection<t1_logins_tb> t1_logins_tb { get; set; }
        public virtual ICollection<t4_usuario_papel_tb> t4_usuario_papel_tb { get; set; }
    }
}
