//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class a5_coach_tb
    {
        public a5_coach_tb()
        {
            this.a19_ferramenta_tb = new HashSet<a19_ferramenta_tb>();
            this.a23_especialidade_tb = new HashSet<a23_especialidade_tb>();
            this.a24_formacao_tb = new HashSet<a24_formacao_tb>();
            this.a9_processo_coaching_tb = new HashSet<a9_processo_coaching_tb>();
        }
    
        public string ID_USUARIO { get; set; }
        public int ID_COACH { get; set; }
    
        public virtual ICollection<a19_ferramenta_tb> a19_ferramenta_tb { get; set; }
        public virtual ICollection<a23_especialidade_tb> a23_especialidade_tb { get; set; }
        public virtual ICollection<a24_formacao_tb> a24_formacao_tb { get; set; }
        public virtual a4_usuario_tb a4_usuario_tb { get; set; }
        public virtual ICollection<a9_processo_coaching_tb> a9_processo_coaching_tb { get; set; }
    }
}
