//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class a6_coachee_tb
    {
        public a6_coachee_tb()
        {
            this.t8_preenchimento_ferramenta_tb = new HashSet<t8_preenchimento_ferramenta_tb>();
            this.a8_fragilidade_tb = new HashSet<a8_fragilidade_tb>();
            this.a7_ponto_forte_tb = new HashSet<a7_ponto_forte_tb>();
            this.a9_processo_coaching_tb = new HashSet<a9_processo_coaching_tb>();
        }
    
        public int ID_COACHEE { get; set; }
        public string ID_USUARIO { get; set; }
        public string PROFISSAO_COACHEE { get; set; }
    
        public virtual a4_usuario_tb a4_usuario_tb { get; set; }
        public virtual ICollection<t8_preenchimento_ferramenta_tb> t8_preenchimento_ferramenta_tb { get; set; }
        public virtual ICollection<a8_fragilidade_tb> a8_fragilidade_tb { get; set; }
        public virtual ICollection<a7_ponto_forte_tb> a7_ponto_forte_tb { get; set; }
        public virtual ICollection<a9_processo_coaching_tb> a9_processo_coaching_tb { get; set; }
    }
}
