//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class a7_ponto_forte_tb
    {
        public int ID_PONTO_FORTE { get; set; }
        public int ID_COACHEE { get; set; }
        public string PONTO_FORTE { get; set; }
        public string CLASSE_PONTO_FORTE { get; set; }
        public string DESCRICAO_PONTO_FORTE { get; set; }
    
        public virtual a6_coachee_tb a6_coachee_tb { get; set; }
    }
}
