//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class a9_processo_coaching_tb
    {
        public a9_processo_coaching_tb()
        {
            this.a10_orcamento_tb = new HashSet<a10_orcamento_tb>();
            this.a11_sessao_tb = new HashSet<a11_sessao_tb>();
            this.a13_plano_acao_tb = new HashSet<a13_plano_acao_tb>();
            this.t5_indicador_desempenho_tb = new HashSet<t5_indicador_desempenho_tb>();
            this.a6_coachee_tb = new HashSet<a6_coachee_tb>();
            this.a18_servico_tb = new HashSet<a18_servico_tb>();
        }
    
        public int ID_PROCESSO { get; set; }
        public int ID_COACH { get; set; }
        public System.DateTime DATA_INICIO_PROCESSO { get; set; }
        public Nullable<System.DateTime> DATA_FIM_PROCESSO { get; set; }
        public string MODALIDADE_PROCESSO { get; set; }
        public string OBSERVACAO_PROCESSO { get; set; }
    
        public virtual ICollection<a10_orcamento_tb> a10_orcamento_tb { get; set; }
        public virtual ICollection<a11_sessao_tb> a11_sessao_tb { get; set; }
        public virtual ICollection<a13_plano_acao_tb> a13_plano_acao_tb { get; set; }
        public virtual a5_coach_tb a5_coach_tb { get; set; }
        public virtual ICollection<t5_indicador_desempenho_tb> t5_indicador_desempenho_tb { get; set; }
        public virtual ICollection<a6_coachee_tb> a6_coachee_tb { get; set; }
        public virtual ICollection<a18_servico_tb> a18_servico_tb { get; set; }
    }
}
