//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class t2_claims_tb
    {
        public int ID_CLAIMS { get; set; }
        public string ID_USUARIO { get; set; }
        public string CLAIMTYPE { get; set; }
        public string CLAIMVALUE { get; set; }
        public string IDENTITYUSER_ID { get; set; }
    
        public virtual a4_usuario_tb a4_usuario_tb { get; set; }
    }
}
