//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachingPlan.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class t8_preenchimento_ferramenta_tb
    {
        public int ID_COACHEE { get; set; }
        public int ID_FERRAMENTA { get; set; }
        public System.DateTime Data_Avaliação { get; set; }
    
        public virtual a19_ferramenta_tb a19_ferramenta_tb { get; set; }
        public virtual a6_coachee_tb a6_coachee_tb { get; set; }
    }
}
